### ISSUE TITLE
Fix local project reference to nuget or github submodule.

### ISSUE THREAD

**Issue by CarnageMarkus** [kirides/DaedalusLanguageServer#1]
Currently projects are referencing yours modified "local" daedalus compiler.
We need to either make nuget package for compiler, or maybe use [Paket](https://fsprojects.github.io/Paket/index.html) to automatically download dependencies.

**Comment by kirides** [comment]
For now i added the whole modified daedaluscompiler project to this project. Might change that to a submodule based on a separate fork, but not now.

Later i hope that the DaedalusCompiler team publishes a NuGet.

**Comment by CarnageMarkus** [comment]
nugets are available on nuget.org 
https://www.nuget.org/packages/DaedalusLib/
https://www.nuget.org/packages/DaedalusCompiler/

you can easily host you modified compiler on nuget. All you need is to set up post build action to package nuget and upload it.
